// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1990QD58ZWWkZs-2jwEKh6VtKtcv1FB0',
    appId: '1:645491861213:web:bb1e196baa16b453dd9d34',
    messagingSenderId: '645491861213',
    projectId: 'denebcorp-70067',
    authDomain: 'denebcorp-70067.firebaseapp.com',
    storageBucket: 'denebcorp-70067.firebasestorage.app',
    measurementId: 'G-MZLYM8HRKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqHS9cuxCGDEj3_GPjhoD9IBEL979rrqE',
    appId: '1:645491861213:android:a6beb9f2cf8e278add9d34',
    messagingSenderId: '645491861213',
    projectId: 'denebcorp-70067',
    storageBucket: 'denebcorp-70067.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmnM-91kcuR2DLGP1iGg-ynkw03TMTf1Q',
    appId: '1:645491861213:ios:b615276bfec4d4a0dd9d34',
    messagingSenderId: '645491861213',
    projectId: 'denebcorp-70067',
    storageBucket: 'denebcorp-70067.firebasestorage.app',
    iosClientId: '645491861213-jl6g5jldj7hnbfn58bclgmesir00bv6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.iPet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmnM-91kcuR2DLGP1iGg-ynkw03TMTf1Q',
    appId: '1:645491861213:ios:b615276bfec4d4a0dd9d34',
    messagingSenderId: '645491861213',
    projectId: 'denebcorp-70067',
    storageBucket: 'denebcorp-70067.firebasestorage.app',
    iosClientId: '645491861213-jl6g5jldj7hnbfn58bclgmesir00bv6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.iPet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1990QD58ZWWkZs-2jwEKh6VtKtcv1FB0',
    appId: '1:645491861213:web:bb1e196baa16b453dd9d34',
    messagingSenderId: '645491861213',
    projectId: 'denebcorp-70067',
    authDomain: 'denebcorp-70067.firebaseapp.com',
    storageBucket: 'denebcorp-70067.firebasestorage.app',
    measurementId: 'G-MZLYM8HRKK',
  );
}
